name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dotnet-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        configuration: [ Release ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore .NET dependencies
      run: |
        dotnet restore
    - name: Build .NET
      run: |
        dotnet build --no-restore --configuration ${{ matrix.configuration }}
    - name: Test .NET
      run: |
        dotnet test --no-build --verbosity normal --configuration ${{ matrix.configuration }}

